apiVersion: v1    
kind: Pod     
metadata:
  name: <podName>
  namespace: <namespaceName>
  lables:
    key: <value> 
    key: <value> 
spec:
  containers:
  - name: containerName   
    image: imageName  
    ports:
    - containerPort: podNumber  
---
pod.yml 
Manifest = kams 
apiVersion: v1    
kind: Pod     
metadata:
  name: webapp 
  namespace: dev 
  lables:
    app: weapp  
spec:
  containers:
  - name: webapp   
    image: mylandmarktech/maven-web-app   
    ports:
    - containerPort: 8080   

#Example 2 for Pod
    pod.yml:  kams  
=================
apiVersion: v1        
kind: Pod    
metadata:
  annotations:   
  name: myapp   
  labels:
    app: tesla 
    app: fe    
spec:
  containers:
  - name: webapp
    image: mylandmarktech/java-web-app    
    ports:
    - containerPort: 8080            
---
apiVersion: v1
kind: Service
metadata:
  name: myappsvc
spec:
  type: ClusterIP  
  selector:
    app: tesla 
    app: fe 
  ports:
    - port: 80 
      targetPort: 8080 